import { chromium } from "playwright";
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
await page.addInitScript(() => { try { localStorage.setItem("onboarded", "1"); } catch (e) {} });
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message));
await page.goto("http://localhost:4318/#/garden");
await wait(900);
await page.getByRole("button", { name: "Next", exact: true }).click();
await page.getByRole("button", { name: "Open the market" }).click();
await wait(300);
await page.getByRole("button", { name: "Plant 3" }).first().click();
await wait(500);
await page.getByRole("button", { name: "Start the season" }).click();
await page.getByText("Meet the co-op field.").waitFor();
await page.getByRole("button", { name: "Start time" }).click();
await wait(2500);
await page.getByRole("button", { name: "Pause" }).click();
await wait(300);
await page.getByText("Pumpkin").last().click();
await wait(300);
await page.getByRole("button", { name: "Transplant half" }).click();
await wait(450);
await page.screenshot({ path: new URL("./shots/garden/cart.png", import.meta.url).pathname });
console.log("cart shot");
await browser.close();
