import { chromium } from "playwright";
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message));
const OUT = new URL("./shots/garden/", import.meta.url).pathname;
import { mkdirSync } from "fs";
mkdirSync(OUT, { recursive: true });

await page.goto("http://localhost:4318/#/garden");
await wait(1000);
await page.screenshot({ path: OUT + "intro.png" });
await page.getByRole("button", { name: "Next", exact: true }).click();
await wait(300);
await page.getByRole("button", { name: "Open the market" }).click();
await wait(400);
await page.screenshot({ path: OUT + "market.png" });
await page.getByRole("button", { name: "Plant 3" }).first().click();
await wait(700);
await page.getByRole("button", { name: "Plant 1" }).first().click();
await wait(500);
await page.screenshot({ path: OUT + "planted.png" });
await page.getByRole("button", { name: "Start the season" }).click();
await wait(400);
await page.screenshot({ path: OUT + "coop.png" });
await page.getByRole("button", { name: "Start time" }).click();
await page.getByText("The sky has gone gray.").waitFor({ timeout: 40000 });
await wait(400);
await page.screenshot({ path: OUT + "warn.png" });
await page.getByRole("button", { name: "Okay" }).click();
await page.getByText("What do you do?").waitFor({ timeout: 30000 });
await wait(600);
await page.screenshot({ path: OUT + "frost.png" });
await page.getByRole("button", { name: "Keep tending" }).click();
await wait(30000);
await page.screenshot({ path: OUT + "end.png" });
console.log("garden walk complete");
await browser.close();
