import { chromium } from "playwright";
const B = "https://marlonedwards.github.io/share-garden-prototypes/#";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1360, height: 1000 }, deviceScaleFactor: 2 });
const errs = [];
p.on("pageerror", e => errs.push("PAGEERR: " + e.message));
p.on("console", m => { if (m.type() === "error") errs.push("CONSOLE: " + m.text()); });
await p.goto(B + "/", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
const h1 = await p.textContent("h1").catch(() => null);
await p.goto(B + "/garden", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
await p.getByText("Tomatoes").first().click().catch(()=>{});
await p.waitForTimeout(1500);
await p.screenshot({ path: "tools/shots/live-garden.png" });
await p.goto(B + "/flows", { waitUntil: "networkidle" });
await p.waitForTimeout(2500);
const hasCanvas = await p.locator("canvas").count();
await p.screenshot({ path: "tools/shots/live-flows.png" });
console.log("landing h1:", JSON.stringify(h1));
console.log("flows canvas count:", hasCanvas);
console.log("errors:", errs.length ? errs.slice(0,6).join("\n") : "none");
await b.close();
