import { chromium } from "playwright";
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 950 }, deviceScaleFactor: 2 });
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message));
await page.goto("http://localhost:4318/#/orb?beat=mid");
await wait(1500);
await page.getByText("Nova Systems").last().click();
await wait(400);
await page.screenshot({ path: "/Users/marlon/Documents/share-garden-prototypes/tools/shots/orb/trade-open.png" });
await page.getByText("Sell half").click();
await wait(1200);
await page.getByText("Volt Energy").last().click();
await wait(300);
await page.getByRole("button", { name: /Buy \$250/ }).last().click();
await wait(1400);
await page.screenshot({ path: "/Users/marlon/Documents/share-garden-prototypes/tools/shots/orb/trade-after.png" });
console.log("done");
await browser.close();
